Iter19
gtgaleevtimur/reduction-url-service pull request #56
Opened 2023-01-24 14:07 UTC by gtgaleevtimur

2023-01-25 12:17 UTC, Perederey requested changes
Отлично, но нужно
1) Добавить тест для аналайзера
2) Не вижу pprof файлов

:)

2023-01-25 12:17 UTC, Perederey commented on cmd/shortener/main.go
> +	buildCommit  = "1.0.0"
должно быть N/A

2023-01-25 12:17 UTC, Perederey commented on cmd/staticlint/analyzer/analyzer.go
> +	return nil, nil
а тестик? ;)

2023-01-25 12:17 UTC, Perederey commented on cmd/staticlint/config.json
> +}
тут пропустил конец-строки
это последовательность символов, обозначающая конец строки текста в коде. EOL важны для запросов для PR, поскольку они определяют, как текстовые файлы отображаются и обрабатываются в различных операционных системах.
Windows использует комбинацию символов (CR) и перевода строки (LF) для обозначения конца строки, в то время как Linux и macOS используют только символ перевода строки (LF).
Представь, если разработчик создает файл на Windows, а затем отправляет запрос на исправление с этим файлом, файл будет содержать CR+LF EOL. Но если этот файл затем будет извлечен и объединен в репозиторий на macOS, символы CR вызовут проблемы при редактировании)
По этой причине для PR важно, чтобы текстовые файлы были последовательны в использовании EOL.
IDE можно настроить чтобы перед запуском он добавлял такую штуку

2023-01-25 12:17 UTC, Perederey commented on cmd/staticlint/main.go
> +	"github.com/gtgaleevtimur/reduction-url-service/cmd/staticlint/analyzer"
👍

2023-01-25 12:26 UTC, gtgaleevtimur commented
> 

pprof файлы в папке profiles( base.pprof , result.pprof)

2023-01-26 10:02 UTC, Perederey approved these changes
увидел) Теперь все ок)

2023-01-27 12:00 UTC, merged